import { StyleSheet } from 'react-native';

export const C = {
  teal: '#14b8a6',
  blue: '#3b82f6',
  green: '#10b981',
  amber: '#f59e0b',
  coral: '#f43f5e',
  bg: '#0B0F19',
  white: '#ffffff',
  slate: '#94a3b8',
  border: '#1e293b',
  surfaceAlt: '#151f32',
  black: '#ffffff',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: C.bg,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  // Date navigation
  dateHeaderCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: C.border,
  },
  dateHeaderTopRow: {
    marginBottom: 8,
  },
  dateEyebrow: {
    fontSize: 12,
    fontWeight: '700',
    color: C.teal,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dateMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.teal,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navButtonDisabled: {
    backgroundColor: C.border,
  },
  dateContent: {
    alignItems: 'center',
  },
  dateDay: {
    fontSize: 18,
    fontWeight: '800',
    color: C.black,
  },
  dateText: {
    fontSize: 14,
    color: C.slate,
    marginTop: 2,
  },
  dateHint: {
    fontSize: 11,
    color: C.slate,
    marginTop: 2,
  },
  // Nutrition Summary
  darkCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: C.border,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  iconBubble: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(20, 184, 166, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  tealIconBubble: {
    backgroundColor: 'rgba(20, 184, 166, 0.1)',
  },
  blueIconBubble: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  redIconBubble: {
    backgroundColor: 'rgba(244, 63, 94, 0.1)',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: C.black,
  },
  cardSubtitle: {
    fontSize: 12,
    color: C.slate,
    marginTop: 2,
  },
  donutOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  donutValue: {
    fontSize: 22,
    fontWeight: '800',
    color: C.black,
  },
  nutritionMeta: {
    fontSize: 10,
    color: C.slate,
    marginTop: 4,
  },
  nutrientGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  nutrientTile: {
    width: '48%',
    backgroundColor: C.bg,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  itemContainer: {},
  circleValuesContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  nutrientName: {
    fontSize: 11,
    color: C.slate,
    marginTop: 2,
  },
  // Input Section Card
  inputSectionCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: C.border,
  },
  photoButton: {
    backgroundColor: 'rgba(20, 184, 166, 0.1)',
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: C.teal,
    borderStyle: 'dashed',
  },
  photoButtonText: {
    color: C.teal,
    fontWeight: '700',
    fontSize: 14,
  },
  nutrientValueRow: {},
  searchInput: {
    backgroundColor: C.bg,
    borderRadius: 12,
    height: 48,
    borderWidth: 1.5,
    borderColor: C.border,
    paddingHorizontal: 12,
    fontSize: 14,
    color: C.white,
    marginBottom: 12,
  },
  searchInputContent: {},
  addButton: {
    backgroundColor: C.teal,
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: C.teal,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: C.teal,
  },
  checkboxCheck: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  checkboxLabel: {
    fontSize: 14,
    color: C.black,
  },
  // Section Title Row
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 8,
  },
  sectionTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: C.black,
  },
  sectionCount: {
    fontSize: 12,
    color: C.slate,
    fontWeight: '600',
  },
  // Meal logs List
  filterScrollContent: {
    paddingVertical: 4,
    marginBottom: 12,
  },
  filterTab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  filterTabActive: {
    backgroundColor: C.teal,
    borderColor: C.teal,
  },
  filterIconWrap: {
    marginRight: 6,
  },
  filterIconWrapActive: {},
  filterLabel: {
    fontSize: 13,
    color: C.slate,
    fontWeight: '600',
  },
  filterLabelActive: {
    color: '#ffffff',
  },
  mealCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  mealHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  mealNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  mealName: {
    fontSize: 15,
    fontWeight: '700',
    color: C.black,
  },
  mealCalories: {
    fontSize: 14,
    fontWeight: '700',
    color: C.teal,
  },
  macroRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  macroChip: {
    backgroundColor: '#1E293B',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginRight: 6,
    marginBottom: 6,
  },
  macroChipText: {
    fontSize: 11,
    color: C.slate,
    fontWeight: '600',
  },
  emptyCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
  },
  emptyText: {
    fontSize: 14,
    color: C.slate,
  },
  sectionSpacing: {
    marginTop: 16,
  },
  alertText: {
    fontSize: 13,
    color: C.slate,
    lineHeight: 18,
  },
  // Modal Style
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: C.surfaceAlt,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: C.border,
    elevation: 10,
  },
  cancel: {
    color: C.slate,
    fontWeight: '700',
    marginTop: 16,
    fontSize: 14,
  },
  // Compliance
  complianceSection: {
    alignItems: 'center',
    marginVertical: 16,
  },
  complianceBadge: {
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  compliantBadge: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
  },
  notCompliantBadge: {
    backgroundColor: 'rgba(244, 63, 94, 0.1)',
  },
  complianceText: {
    fontSize: 11,
    fontWeight: '700',
  },
  compliantText: {
    color: C.green,
  },
  notCompliantText: {
    color: C.coral,
  },
  complianceMetricValue: {
    fontSize: 18,
    fontWeight: '800',
    color: C.black,
  },
  progressTrack: {
    height: 8,
    backgroundColor: '#1E293B',
    borderRadius: 4,
    overflow: 'hidden',
    marginTop: 6,
    marginBottom: 12,
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  analysisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  analysisValue: {
    fontSize: 14,
    fontWeight: '600',
    color: C.black,
  },
  analysisTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: C.black,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  analysisSub: {
    fontSize: 12,
    color: C.slate,
    marginTop: 2,
  },
  analysisSection: {
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: C.border,
    paddingTop: 12,
  },
  analysisCardGreen: {
    backgroundColor: 'rgba(16, 185, 129, 0.05)',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: C.green,
  },
  analysisCardRed: {
    backgroundColor: 'rgba(244, 63, 94, 0.05)',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: C.coral,
  },
  analysisCardTeal: {
    backgroundColor: 'rgba(20, 184, 166, 0.05)',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: C.teal,
  },
  // Planner
  plannerCalendarRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  plannerDateChip: {
    width: 60,
    height: 70,
    backgroundColor: '#1E293B',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  plannerDateChipActive: {
    backgroundColor: C.teal,
    borderColor: C.teal,
  },
  plannerDateDay: {
    fontSize: 12,
    color: C.slate,
    fontWeight: '600',
  },
  plannerDateDayActive: {
    color: '#ffffff',
  },
  plannerDateText: {
    fontSize: 18,
    fontWeight: '800',
    color: C.black,
    marginTop: 2,
  },
  plannerDateTextActive: {
    color: '#ffffff',
  },
  plannerInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  flexInput: {
    flex: 1,
    marginRight: 8,
    marginBottom: 0,
  },
  plannerListCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: C.border,
  },
  plannerMealRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  plannerMealName: {
    fontSize: 14,
    fontWeight: '600',
    color: C.black,
    flex: 1,
    marginRight: 8,
  },
  replaceButton: {
    backgroundColor: 'rgba(20, 184, 166, 0.1)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  replaceButtonText: {
    color: C.teal,
    fontSize: 12,
    fontWeight: '700',
  },
  deleteButton: {
    backgroundColor: 'rgba(244, 63, 94, 0.1)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  deleteButtonText: {
    color: C.coral,
    fontSize: 12,
    fontWeight: '700',
  },
  saveButton: {
    backgroundColor: C.teal,
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  saveButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
  savedPlanCard: {
    backgroundColor: C.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  savedPlanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    paddingBottom: 8,
  },
  savedPlanTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: C.black,
  },
  savedPlanDate: {
    fontSize: 11,
    color: C.slate,
  },
  savedSlotRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  savedSlotLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: C.slate,
    width: 80,
  },
  savedSlotValue: {
    fontSize: 12,
    color: C.black,
    flex: 1,
    textAlign: 'right',
  },
  headerContainer: {
    backgroundColor: '#0B0F19',
    borderBottomColor: '#1E293B',
  },
  headerTitle: {
    color: '#FFFFFF',
  },
  headerButton: {
    backgroundColor: '#0F172A',
    borderColor: '#1E293B',
  },
  headerIcon: {
    color: '#FFFFFF',
  },
});
