import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    paddingBottom: 40,
  },
  header: {
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    marginBottom: theme.spacing.md,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  headerTitleBlock: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800' as any,
    color: theme.colors.text,
  },
  headerSub: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
  },
  statusPillDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '700' as any,
  },
  headerMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: theme.spacing.md,
    paddingTop: theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  headerMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: theme.spacing.lg,
  },
  headerMetaText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginLeft: 6,
  },
  emptySlot: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    marginHorizontal: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  emptySlotText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginTop: 10,
    fontWeight: '500' as any,
  },
  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  cardWrapper: {
    width: '48%',
    marginBottom: theme.spacing.md,
    paddingHorizontal: theme.spacing.sm,
  },
  metricsSectionTitle: {
    fontSize: 15,
    fontWeight: '800' as any,
    color: theme.colors.text,
    marginHorizontal: theme.spacing.lg,
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  syncSection: {
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  syncButton: {
    width: '100%',
    marginTop: theme.spacing.md,
  },
  historySection: {
    marginTop: theme.spacing.lg,
  },
  sessionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: theme.spacing.md,
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sessionInfo: {
    flex: 1,
  },
  sessionTitle: {
    fontSize: 14,
    fontWeight: '700' as any,
    color: theme.colors.text,
  },
  sessionDetails: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginTop: 4,
  },
  sessionTimeBadge: {
    backgroundColor: theme.colors.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  sessionTimeText: {
    fontSize: 11,
    color: theme.colors.primaryDark,
    fontWeight: '700' as any,
  },
  guideCard: {
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
    backgroundColor: '#EEF2FF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  guideTitle: {
    fontSize: 14,
    fontWeight: '800' as any,
    color: '#312E81',
    marginBottom: 8,
  },
  guideText: {
    fontSize: 12,
    color: '#4338CA',
    lineHeight: 18,
    marginBottom: 12,
  },
  guideButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  guideButtonHC: {
    backgroundColor: '#4F46E5',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    flex: 0.48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guideButtonGF: {
    backgroundColor: '#10B981',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    flex: 0.48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guideButtonText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700' as any,
  },
  metricCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
    height: 140,
    justifyContent: 'space-between',
  },
  metricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  metricIconContainer: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  metricTitle: {
    fontSize: 12,
    fontWeight: '700' as any,
    color: '#64748B',
  },
  metricValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  metricValue: {
    fontSize: 22,
    fontWeight: '800' as any,
    color: '#0F172A',
  },
  metricUnit: {
    fontSize: 12,
    fontWeight: '600' as any,
    color: '#94A3B8',
    marginLeft: 4,
  },
  metricProgressContainer: {
    marginTop: 10,
  },
  metricProgressBackground: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F1F5F9',
    overflow: 'hidden',
  },
  metricProgressBar: {
    height: '100%',
    borderRadius: 3,
  },
  metricProgressText: {
    fontSize: 10,
    fontWeight: '600' as any,
    color: '#64748B',
    marginTop: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '100%',
    maxWidth: 340,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  modalIconRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800' as any,
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalSub: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 20,
  },
  modalActionsList: {
    width: '100%',
    marginBottom: 16,
  },
  modalActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  modalActionInfo: {
    flex: 1,
    marginRight: 10,
  },
  modalActionTitle: {
    fontSize: 13,
    fontWeight: '700' as any,
    color: '#0F172A',
  },
  modalActionText: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  modalDownloadBtn: {
    backgroundColor: '#4F46E5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  modalDownloadBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700' as any,
  },
  modalCloseBtn: {
    paddingVertical: 10,
    width: '100%',
    alignItems: 'center',
  },
  modalCloseBtnText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600' as any,
  },
  // Success / Failure Status Modal Styles
  statusIconRingSuccess: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusIconRingFailure: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: '800' as any,
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 8,
  },
  statusSub: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  statusButtonSuccess: {
    backgroundColor: '#10B981',
    paddingVertical: 12,
    width: '100%',
    borderRadius: 12,
    alignItems: 'center',
  },
  statusButtonFailure: {
    backgroundColor: '#EF4444',
    paddingVertical: 12,
    width: '100%',
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 8,
  },
  statusButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700' as any,
  },
  historyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 14,
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  historyDateBox: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  historyMonthText: {
    fontSize: 9,
    fontWeight: '800' as any,
    color: '#94A3B8',
    textTransform: 'uppercase',
  },
  historyDayText: {
    fontSize: 18,
    fontWeight: '800' as any,
    color: '#0F172A',
    marginTop: -2,
  },
  historyContent: {
    flex: 1,
    justifyContent: 'center',
  },
  historyDayName: {
    fontSize: 14,
    fontWeight: '800' as any,
    color: '#0F172A',
    marginBottom: 4,
  },
  historyStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  historyStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  historyStatText: {
    fontSize: 11,
    fontWeight: '600' as any,
    color: '#475569',
    marginLeft: 4,
  },
  historyStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    minWidth: 70,
    alignItems: 'center',
  },
  historyStatusText: {
    fontSize: 10,
    fontWeight: '800' as any,
  },
  // Custom styled exercise session cards
  workoutCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 14,
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  workoutIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  workoutInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  workoutTitle: {
    fontSize: 14,
    fontWeight: '800' as any,
    color: '#0F172A',
  },
  workoutSource: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 2,
  },
  workoutDurationPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  workoutDurationText: {
    fontSize: 11,
    fontWeight: '800' as any,
    color: '#475569',
  },
  metricIconText: {
    fontSize: 18,
  },
  metricSpacer: {
    height: 32,
  },
  onboardingContainer: {
    paddingHorizontal: 16,
  },
  verticalSpacer: {
    height: 16,
  },
  actionBtnMargin: {
    marginTop: 12,
  },
  syncTitle: {
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '700' as any,
    textAlign: 'center',
  },
  syncSubText: {
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    marginTop: 4,
  },
  workoutIconText: {
    fontSize: 20,
  },
  historyEmojiText: {
    fontSize: 12,
  },
  modalIconText: {
    fontSize: 28,
  },
  statusIconText: {
    fontSize: 32,
  },
});
