export const ACTIVITY_TYPES = {
  RUNNING: 'Running',
  WALKING: 'Walking',
  CYCLING: 'Cycling',
  SWIMMING: 'Swimming',
  YOGA: 'Yoga',
  WORKOUT: 'Workout',
  HIKING: 'Hiking',
  ROWING: 'Rowing',
  CALISTHENICS: 'Push-ups / Calisthenics',
  PLANK: 'Plank / Core',
  WEIGHT_LIFTING: 'Deadlifts / Weights',
  PILATES: 'Pilates',
  BADMINTON: 'Badminton',
  FOOTBALL: 'Football',
  TABLE_TENNIS: 'Table Tennis',
  SPINNING: 'Indoor Spinning',
  STRETCHING: 'Stretching',
  AEROBICS: 'Aerobic Dance',
  ZUMBA: 'Zumba Gold',
  KABADDI: 'Kabaddi',
  CRICKET: 'Cricket',
  OTHER: 'Other',
} as const;

export type ActivityType = string;

export const ACTIVITY_METRICS = {
  [ACTIVITY_TYPES.RUNNING]: 'km',
  [ACTIVITY_TYPES.WALKING]: 'steps',
  [ACTIVITY_TYPES.CYCLING]: 'km',
  [ACTIVITY_TYPES.SWIMMING]: 'm',
  [ACTIVITY_TYPES.YOGA]: 'mins',
  [ACTIVITY_TYPES.WORKOUT]: 'mins',
  [ACTIVITY_TYPES.HIKING]: 'km',
  [ACTIVITY_TYPES.ROWING]: 'km',
  [ACTIVITY_TYPES.CALISTHENICS]: 'reps',
  [ACTIVITY_TYPES.PLANK]: 'mins',
  [ACTIVITY_TYPES.WEIGHT_LIFTING]: 'sets',
  [ACTIVITY_TYPES.PILATES]: 'mins',
  [ACTIVITY_TYPES.BADMINTON]: 'mins',
  [ACTIVITY_TYPES.FOOTBALL]: 'mins',
  [ACTIVITY_TYPES.TABLE_TENNIS]: 'mins',
  [ACTIVITY_TYPES.SPINNING]: 'mins',
  [ACTIVITY_TYPES.STRETCHING]: 'mins',
  [ACTIVITY_TYPES.AEROBICS]: 'mins',
  [ACTIVITY_TYPES.ZUMBA]: 'mins',
  [ACTIVITY_TYPES.KABADDI]: 'mins',
  [ACTIVITY_TYPES.CRICKET]: 'mins',
  [ACTIVITY_TYPES.OTHER]: 'mins',
} as const;

export interface WellnessActivity {
  name: string;
  emoji: string;
  metric: 'km' | 'steps' | 'm' | 'mins' | 'reps' | 'sets';
  baseMET: number;
  category: 'distance' | 'strength' | 'duration';
  color: string;
}

export const WELLNESS_ACTIVITIES_REGISTRY: WellnessActivity[] = [
  // Outdoors & Hiking
  { name: 'Hiking', emoji: '🥾', metric: 'km', baseMET: 6.0, category: 'distance', color: '#16A34A' },
  { name: 'Mountain Trekking', emoji: '🏔️', metric: 'km', baseMET: 7.5, category: 'distance', color: '#059669' },
  { name: 'Backpacking', emoji: '🎒', metric: 'km', baseMET: 7.0, category: 'distance', color: '#15803D' },
  { name: 'Snowshoeing', emoji: '❄️', metric: 'km', baseMET: 8.0, category: 'distance', color: '#0F766E' },
  { name: 'Nordic Walking', emoji: '🦯', metric: 'steps', baseMET: 4.5, category: 'distance', color: '#16A34A' },
  { name: 'Trail Walking', emoji: '🌲', metric: 'steps', baseMET: 4.8, category: 'distance', color: '#15803D' },
  { name: 'Nature Stroll', emoji: '🌿', metric: 'steps', baseMET: 3.5, category: 'distance', color: '#10B981' },
  { name: 'Geocaching', emoji: '🗺️', metric: 'steps', baseMET: 3.2, category: 'distance', color: '#047857' },
  { name: 'Hill Climbing', emoji: '⛰️', metric: 'km', baseMET: 6.5, category: 'distance', color: '#064E3B' },
  { name: 'Desert Trekking', emoji: '🌵', metric: 'km', baseMET: 6.8, category: 'distance', color: '#D97706' },
  { name: 'Forest Rucking', emoji: '🪨', metric: 'km', baseMET: 7.2, category: 'distance', color: '#1E3A8A' },
  { name: 'Camp Walk', emoji: '⛺', metric: 'steps', baseMET: 3.0, category: 'distance', color: '#475569' },
  { name: 'Rock Scrambling', emoji: '🧗‍♂️', metric: 'mins', baseMET: 5.5, category: 'duration', color: '#334155' },
  { name: 'Glacier Trekking', emoji: '🧊', metric: 'km', baseMET: 8.5, category: 'distance', color: '#0284C7' },
  { name: 'Wilderness Survival Track', emoji: '🔥', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#78350F' },

  // Running & Jogging
  { name: 'Running', emoji: '🏃', metric: 'km', baseMET: 9.8, category: 'distance', color: '#EF4444' },
  { name: 'Jogging', emoji: '🏃‍♂️', metric: 'km', baseMET: 7.0, category: 'distance', color: '#F87171' },
  { name: 'Trail Running', emoji: '🏃‍♀️', metric: 'km', baseMET: 10.5, category: 'distance', color: '#DC2626' },
  { name: 'Sprinting', emoji: '⚡', metric: 'm', baseMET: 15.0, category: 'distance', color: '#B91C1C' },
  { name: 'Treadmill Running', emoji: '🏃‍♂️', metric: 'km', baseMET: 9.0, category: 'distance', color: '#EF4444' },
  { name: 'Track Running', emoji: '🏟️', metric: 'km', baseMET: 9.5, category: 'distance', color: '#991B1B' },
  { name: 'Sand Running', emoji: '🏖️', metric: 'km', baseMET: 11.0, category: 'distance', color: '#F59E0B' },
  { name: 'Obstacle Course', emoji: '🚧', metric: 'mins', baseMET: 10.0, category: 'duration', color: '#D97706' },
  { name: 'Marathon Running', emoji: '🏅', metric: 'km', baseMET: 10.2, category: 'distance', color: '#EF4444' },
  { name: 'Tempo Running', emoji: '⏱️', metric: 'km', baseMET: 10.0, category: 'distance', color: '#7F1D1D' },
  { name: 'Interval Sprints', emoji: '🔄', metric: 'mins', baseMET: 12.0, category: 'duration', color: '#991B1B' },
  { name: 'Fartlek Run', emoji: '🐆', metric: 'km', baseMET: 9.6, category: 'distance', color: '#EA580C' },
  { name: 'Uphill Sprints', emoji: '📈', metric: 'm', baseMET: 14.0, category: 'distance', color: '#B91C1C' },
  { name: 'Stair Running', emoji: '📶', metric: 'mins', baseMET: 11.5, category: 'duration', color: '#EF4444' },
  { name: 'Ultra Marathon', emoji: '🌍', metric: 'km', baseMET: 9.0, category: 'distance', color: '#7F1D1D' },

  // Walking & Commuting
  { name: 'Walking', emoji: '🚶', metric: 'steps', baseMET: 4.0, category: 'distance', color: '#3B82F6' },
  { name: 'Power Walking', emoji: '🚶‍♂️', metric: 'steps', baseMET: 5.0, category: 'distance', color: '#2563EB' },
  { name: 'Race Walking', emoji: '🚶‍♀️', metric: 'steps', baseMET: 6.5, category: 'distance', color: '#1D4ED8' },
  { name: 'Commute Stroll', emoji: '💼', metric: 'steps', baseMET: 3.3, category: 'distance', color: '#64748B' },
  { name: 'Treadmill Walking', emoji: '👟', metric: 'steps', baseMET: 3.8, category: 'distance', color: '#3B82F6' },
  { name: 'Dog Walking', emoji: '🐕', metric: 'steps', baseMET: 3.0, category: 'distance', color: '#10B981' },
  { name: 'Mall Walking', emoji: '🛍️', metric: 'steps', baseMET: 2.8, category: 'distance', color: '#475569' },
  { name: 'Sightseeing Walk', emoji: '📷', metric: 'steps', baseMET: 2.5, category: 'distance', color: '#64748B' },
  { name: 'Evening Stroll', emoji: '🌙', metric: 'steps', baseMET: 3.0, category: 'distance', color: '#1E293B' },
  { name: 'Lunch Walk', emoji: '🥪', metric: 'steps', baseMET: 3.2, category: 'distance', color: '#3B82F6' },
  { name: 'Morning Walk', emoji: '🌅', metric: 'steps', baseMET: 3.5, category: 'distance', color: '#0284C7' },
  { name: 'Speed Walking', emoji: '👟', metric: 'steps', baseMET: 4.8, category: 'distance', color: '#2563EB' },
  { name: 'Hiking Path Walk', emoji: '🛤️', metric: 'steps', baseMET: 4.2, category: 'distance', color: '#0D9488' },
  { name: 'Barefoot Beach Walk', emoji: '🏖️', metric: 'steps', baseMET: 4.5, category: 'distance', color: '#F59E0B' },
  { name: 'Casual City Stroll', emoji: '🏙️', metric: 'steps', baseMET: 2.8, category: 'distance', color: '#3B82F6' },

  // Cycling & Spinning
  { name: 'Cycling', emoji: '🚴', metric: 'km', baseMET: 6.0, category: 'distance', color: '#06B6D4' },
  { name: 'Mountain Biking', emoji: '🚵', metric: 'km', baseMET: 8.5, category: 'distance', color: '#0891B2' },
  { name: 'Road Cycling', emoji: '🚴‍♂️', metric: 'km', baseMET: 7.5, category: 'distance', color: '#0E7490' },
  { name: 'Indoor Spinning', emoji: '🚴‍♀️', metric: 'mins', baseMET: 6.8, category: 'duration', color: '#06B6D4' },
  { name: 'Recumbent Cycling', emoji: '🛋️', metric: 'km', baseMET: 5.0, category: 'distance', color: '#0891B2' },
  { name: 'BMX Riding', emoji: '🚲', metric: 'mins', baseMET: 8.5, category: 'duration', color: '#0D9488' },
  { name: 'Unicycling', emoji: '🎪', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#D97706' },
  { name: 'Handcycling', emoji: '♿', metric: 'km', baseMET: 6.0, category: 'distance', color: '#0284C7' },
  { name: 'Bike Commuting', emoji: '🎒', metric: 'km', baseMET: 5.8, category: 'distance', color: '#06B6D4' },
  { name: 'Fat Bike Riding', emoji: '❄️', metric: 'km', baseMET: 9.0, category: 'distance', color: '#0369A1' },
  { name: 'Gravel Grinding', emoji: '🪨', metric: 'km', baseMET: 7.8, category: 'distance', color: '#0F766E' },
  { name: 'Time Trial Cycling', emoji: '⏱️', metric: 'km', baseMET: 10.5, category: 'distance', color: '#0891B2' },
  { name: 'Cycling Hill Climb', emoji: '📈', metric: 'km', baseMET: 9.5, category: 'distance', color: '#0E7490' },
  { name: 'Leisurely Cycle', emoji: '🌸', metric: 'km', baseMET: 4.0, category: 'distance', color: '#0D9488' },
  { name: 'Virtual Cycling Ride', emoji: '🖥️', metric: 'km', baseMET: 6.5, category: 'distance', color: '#06B6D4' },

  // Gym & Strength
  { name: 'Deadlifts / Weights', emoji: '🏋️‍♂️', metric: 'sets', baseMET: 6.0, category: 'strength', color: '#7C3AED' },
  { name: 'Barbell Back Squats', emoji: '🏋️', metric: 'sets', baseMET: 5.5, category: 'strength', color: '#8B5CF6' },
  { name: 'Bench Press', emoji: '🏋️‍♂️', metric: 'sets', baseMET: 5.0, category: 'strength', color: '#6D28D9' },
  { name: 'Overhead Press', emoji: '🏋️‍♀️', metric: 'sets', baseMET: 5.0, category: 'strength', color: '#7C3AED' },
  { name: 'Barbell Rows', emoji: '🏋️‍♂️', metric: 'sets', baseMET: 4.8, category: 'strength', color: '#5B21B6' },
  { name: 'Dumbbell Lunges', emoji: '🏋️‍♀️', metric: 'reps', baseMET: 4.5, category: 'strength', color: '#8B5CF6' },
  { name: 'Dumbbell Bicep Curls', emoji: '💪', metric: 'reps', baseMET: 3.0, category: 'strength', color: '#4F46E5' },
  { name: 'Tricep Extensions', emoji: '💪', metric: 'reps', baseMET: 3.0, category: 'strength', color: '#4338CA' },
  { name: 'Lateral Raises', emoji: '💪', metric: 'reps', baseMET: 2.8, category: 'strength', color: '#6366F1' },
  { name: 'Push-ups / Calisthenics', emoji: '💪', metric: 'reps', baseMET: 3.8, category: 'strength', color: '#4F46E5' },
  { name: 'Pull-ups', emoji: '🧗‍♂️', metric: 'reps', baseMET: 5.0, category: 'strength', color: '#4338CA' },
  { name: 'Chin-ups', emoji: '🧗‍♂️', metric: 'reps', baseMET: 4.8, category: 'strength', color: '#3730A3' },
  { name: 'Dips', emoji: '🦾', metric: 'reps', baseMET: 4.0, category: 'strength', color: '#4F46E5' },
  { name: 'Muscle-ups', emoji: '🦾', metric: 'reps', baseMET: 8.0, category: 'strength', color: '#312E81' },
  { name: 'Handstand Push-ups', emoji: '🤸‍♂️', metric: 'reps', baseMET: 7.5, category: 'strength', color: '#8B5CF6' },
  { name: 'Burpees', emoji: '🐸', metric: 'reps', baseMET: 8.0, category: 'strength', color: '#EF4444' },
  { name: 'Sit-ups', emoji: '🤸', metric: 'reps', baseMET: 3.8, category: 'strength', color: '#0D9488' },
  { name: 'Crunches', emoji: '🤸', metric: 'reps', baseMET: 3.0, category: 'strength', color: '#10B981' },
  { name: 'Russian Twists', emoji: '🌀', metric: 'reps', baseMET: 3.5, category: 'strength', color: '#06B6D4' },
  { name: 'Hanging Leg Raises', emoji: '🧗', metric: 'reps', baseMET: 4.5, category: 'strength', color: '#4F46E5' },
  { name: 'Plank / Core', emoji: '🧘‍♂️', metric: 'mins', baseMET: 3.0, category: 'strength', color: '#0D9488' },
  { name: 'Side Plank', emoji: '🧘‍♀️', metric: 'mins', baseMET: 3.0, category: 'strength', color: '#0D9488' },
  { name: 'Mountain Climbers', emoji: '🧗‍♀️', metric: 'reps', baseMET: 8.0, category: 'strength', color: '#E11D48' },
  { name: 'Leg Press', emoji: '🦿', metric: 'sets', baseMET: 4.0, category: 'strength', color: '#7C3AED' },
  { name: 'Leg Extensions', emoji: '🦿', metric: 'sets', baseMET: 3.0, category: 'strength', color: '#8B5CF6' },
  { name: 'Leg Curls', emoji: '🦿', metric: 'sets', baseMET: 3.0, category: 'strength', color: '#8B5CF6' },
  { name: 'Calf Raises', emoji: '🦿', metric: 'reps', baseMET: 2.5, category: 'strength', color: '#64748B' },
  { name: 'Lat Pulldowns', emoji: '💪', metric: 'sets', baseMET: 3.8, category: 'strength', color: '#4F46E5' },
  { name: 'Cable Flyes', emoji: '🦾', metric: 'sets', baseMET: 3.5, category: 'strength', color: '#4338CA' },
  { name: 'Chest Press Machine', emoji: '🏋️', metric: 'sets', baseMET: 4.0, category: 'strength', color: '#7C3AED' },

  // Functional Conditioning & Cross-Training
  { name: 'Kettlebell Swings', emoji: '🪨', metric: 'reps', baseMET: 6.0, category: 'strength', color: '#F97316' },
  { name: 'Kettlebell Goblet Squats', emoji: '🪨', metric: 'sets', baseMET: 5.5, category: 'strength', color: '#EA580C' },
  { name: 'Kettlebell Turkish Get-ups', emoji: '🤸‍♂️', metric: 'reps', baseMET: 7.0, category: 'strength', color: '#C2410C' },
  { name: 'Slam Balls', emoji: '🏀', metric: 'reps', baseMET: 6.5, category: 'strength', color: '#EF4444' },
  { name: 'Wall Balls', emoji: '🥎', metric: 'reps', baseMET: 7.0, category: 'strength', color: '#DC2626' },
  { name: 'Medicine Ball Twists', emoji: '🌀', metric: 'reps', baseMET: 3.8, category: 'strength', color: '#0D9488' },
  { name: 'Battle Ropes', emoji: '🪢', metric: 'mins', baseMET: 8.0, category: 'strength', color: '#B91C1C' },
  { name: 'Tire Flips', emoji: '🛞', metric: 'reps', baseMET: 9.0, category: 'strength', color: '#7C2D12' },
  { name: 'Farmer Carries', emoji: '🚶‍♂️', metric: 'm', baseMET: 5.0, category: 'distance', color: '#7C3AED' },
  { name: 'Sled Push/Pull', emoji: '🛷', metric: 'm', baseMET: 8.5, category: 'distance', color: '#991B1B' },
  { name: 'Box Jumps', emoji: '📦', metric: 'reps', baseMET: 7.5, category: 'strength', color: '#EF4444' },
  { name: 'Burpee Box Jumps', emoji: '🐸', metric: 'reps', baseMET: 9.0, category: 'strength', color: '#B91C1C' },
  { name: 'Double Unders (Jump Rope)', emoji: '🔄', metric: 'reps', baseMET: 10.0, category: 'strength', color: '#DC2626' },
  { name: 'Single Unders', emoji: '〰️', metric: 'reps', baseMET: 6.0, category: 'strength', color: '#F97316' },
  { name: 'Wall Walks', emoji: '🧗', metric: 'reps', baseMET: 8.0, category: 'strength', color: '#4F46E5' },
  { name: 'Thrusters', emoji: '🏋️', metric: 'reps', baseMET: 9.5, category: 'strength', color: '#EF4444' },
  { name: 'Snatch (Olympic)', emoji: '🏋️‍♂️', metric: 'reps', baseMET: 11.0, category: 'strength', color: '#7C3AED' },
  { name: 'Clean and Jerk', emoji: '🏋️‍♀️', metric: 'reps', baseMET: 11.0, category: 'strength', color: '#7C3AED' },
  { name: 'Power Clean', emoji: '🏋️‍♂️', metric: 'reps', baseMET: 9.0, category: 'strength', color: '#6D28D9' },
  { name: 'Overhead Squats', emoji: '🏋️‍♀️', metric: 'sets', baseMET: 7.5, category: 'strength', color: '#8B5CF6' },

  // Yoga, Pilates & Mind-Body
  { name: 'Yoga', emoji: '🧘', metric: 'mins', baseMET: 3.0, category: 'duration', color: '#10B981' },
  { name: 'Yoga (Vinyasa)', emoji: '🧘‍♀️', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#059669' },
  { name: 'Yoga (Power)', emoji: '🧘‍♂️', metric: 'mins', baseMET: 5.5, category: 'duration', color: '#047857' },
  { name: 'Yoga (Yin)', emoji: '🧘', metric: 'mins', baseMET: 2.0, category: 'duration', color: '#10B981' },
  { name: 'Yoga (Hot)', emoji: '🔥', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#EF4444' },
  { name: 'Pilates', emoji: '🤸', metric: 'mins', baseMET: 3.5, category: 'duration', color: '#DB2777' },
  { name: 'Pilates (Reformer)', emoji: '🤸‍♀️', metric: 'mins', baseMET: 4.5, category: 'duration', color: '#EC4899' },
  { name: 'Tai Chi', emoji: '🧘‍♀️', metric: 'mins', baseMET: 3.0, category: 'duration', color: '#10B981' },
  { name: 'Qigong', emoji: '🧘‍♂️', metric: 'mins', baseMET: 2.5, category: 'duration', color: '#10B981' },
  { name: 'Meditation (Mindful)', emoji: '🧠', metric: 'mins', baseMET: 1.0, category: 'duration', color: '#64748B' },
  { name: 'Meditation (Walking)', emoji: '🚶', metric: 'steps', baseMET: 2.0, category: 'distance', color: '#3B82F6' },
  { name: 'Stretching', emoji: '🙆‍♂️', metric: 'mins', baseMET: 2.3, category: 'duration', color: '#475569' },
  { name: 'Flexibility Routine', emoji: '🤸‍♂️', metric: 'mins', baseMET: 2.5, category: 'duration', color: '#10B981' },
  { name: 'Foam Rolling', emoji: '🪵', metric: 'mins', baseMET: 1.8, category: 'duration', color: '#64748B' },
  { name: 'Mobility Work', emoji: '🔄', metric: 'mins', baseMET: 2.5, category: 'duration', color: '#0D9488' },

  // Swimming & Water Sports
  { name: 'Swimming', emoji: '🏊', metric: 'm', baseMET: 8.0, category: 'distance', color: '#0EA5E9' },
  { name: 'Open Water Swimming', emoji: '🏊‍♂️', metric: 'm', baseMET: 9.5, category: 'distance', color: '#0284C7' },
  { name: 'Water Aerobics', emoji: '🎵', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#0EA5E9' },
  { name: 'Water Jogging', emoji: '🏃‍♂️', metric: 'm', baseMET: 6.0, category: 'distance', color: '#3B82F6' },
  { name: 'Synchronized Swimming', emoji: '👯‍♀️', metric: 'mins', baseMET: 5.5, category: 'duration', color: '#DB2777' },
  { name: 'Snorkeling', emoji: '🤿', metric: 'mins', baseMET: 3.0, category: 'duration', color: '#0EA5E9' },
  { name: 'Scuba Diving', emoji: '🤿', metric: 'mins', baseMET: 4.5, category: 'duration', color: '#1E3A8A' },
  { name: 'Freediving', emoji: '🌊', metric: 'mins', baseMET: 3.0, category: 'duration', color: '#0E7490' },
  { name: 'Kayaking', emoji: '🛶', metric: 'm', baseMET: 5.0, category: 'distance', color: '#F97316' },
  { name: 'Canoeing', emoji: '🛶', metric: 'm', baseMET: 4.0, category: 'distance', color: '#EA580C' },
  { name: 'Rowing', emoji: '🚣', metric: 'km', baseMET: 7.0, category: 'distance', color: '#0284C7' },
  { name: 'Stand Up Paddleboarding (SUP)', emoji: '🏄‍♂️', metric: 'm', baseMET: 4.5, category: 'distance', color: '#06B6D4' },
  { name: 'Dragon Boat', emoji: '🐉', metric: 'm', baseMET: 7.0, category: 'distance', color: '#EF4444' },
  { name: 'Windsurfing', emoji: '⛵', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#0EA5E9' },
  { name: 'Kitesurfing', emoji: '🪁', metric: 'mins', baseMET: 7.5, category: 'duration', color: '#06B6D4' },
  { name: 'Surfing', emoji: '🏄‍♀️', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#0E7490' },
  { name: 'Wakeboarding', emoji: '🏄‍♂️', metric: 'mins', baseMET: 5.5, category: 'duration', color: '#0284C7' },
  { name: 'Water Skiing', emoji: '⛷️', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#0EA5E9' },
  { name: 'Sailing', emoji: '⛵', metric: 'mins', baseMET: 3.0, category: 'duration', color: '#3B82F6' },
  { name: 'Rafting', emoji: '🌊', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#F97316' },

  // Court & Team Sports
  { name: 'Football', emoji: '⚽', metric: 'mins', baseMET: 7.0, category: 'duration', color: '#16A34A' },
  { name: 'Basketball', emoji: '🏀', metric: 'mins', baseMET: 6.5, category: 'duration', color: '#F97316' },
  { name: 'Cricket', emoji: '🏏', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#F59E0B' },
  { name: 'Kabaddi', emoji: '🤼', metric: 'mins', baseMET: 8.0, category: 'duration', color: '#F97316' },
  { name: 'Badminton', emoji: '🏸', metric: 'mins', baseMET: 4.5, category: 'duration', color: '#D97706' },
  { name: 'Table Tennis', emoji: '🏓', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#2563EB' },
  { name: 'Lawn Tennis', emoji: '🎾', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#16A34A' },
  { name: 'Volleyball', emoji: '🏐', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#3B82F6' },
  { name: 'Beach Volleyball', emoji: '🏖️', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#F59E0B' },
  { name: 'Squash', emoji: '🎾', metric: 'mins', baseMET: 12.0, category: 'duration', color: '#EF4444' },
  { name: 'Handball', emoji: '🤾‍♂️', metric: 'mins', baseMET: 8.0, category: 'duration', color: '#DC2626' },
  { name: 'Rugby', emoji: '🏉', metric: 'mins', baseMET: 8.5, category: 'duration', color: '#B91C1C' },
  { name: 'Hockey', emoji: '🏑', metric: 'mins', baseMET: 7.8, category: 'duration', color: '#15803D' },
  { name: 'Lacrosse', emoji: '🥍', metric: 'mins', baseMET: 8.0, category: 'duration', color: '#1D4ED8' },
  { name: 'Ultimate Frisbee', emoji: '🥏', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#F97316' },
  { name: 'Dodgeball', emoji: '🔴', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#EF4444' },
  { name: 'Kickball', emoji: '🎈', metric: 'mins', baseMET: 4.5, category: 'duration', color: '#EA580C' },
  { name: 'Netball', emoji: '🏐', metric: 'mins', baseMET: 5.0, category: 'duration', color: '#4F46E5' },
  { name: 'Water Polo', emoji: '🤽‍♂️', metric: 'mins', baseMET: 10.0, category: 'duration', color: '#0284C7' },

  // Martial Arts & Boxing
  { name: 'Boxing (Sparring)', emoji: '🥊', metric: 'mins', baseMET: 7.8, category: 'duration', color: '#EF4444' },
  { name: 'Boxing (Heavy Bag)', emoji: '🥊', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#DC2626' },
  { name: 'Shadow Boxing', emoji: '🥊', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#F87171' },
  { name: 'Kickboxing', emoji: '🥊', metric: 'mins', baseMET: 10.0, category: 'duration', color: '#B91C1C' },
  { name: 'Muay Thai', emoji: '🥊', metric: 'mins', baseMET: 10.0, category: 'duration', color: '#991B1B' },
  { name: 'Karate', emoji: '🥋', metric: 'mins', baseMET: 7.0, category: 'duration', color: '#F97316' },
  { name: 'Taekwondo', emoji: '🥋', metric: 'mins', baseMET: 7.0, category: 'duration', color: '#EA580C' },
  { name: 'Judo', emoji: '🥋', metric: 'mins', baseMET: 7.5, category: 'duration', color: '#C2410C' },
  { name: 'Brazilian Jiu-Jitsu', emoji: '🥋', metric: 'mins', baseMET: 8.0, category: 'duration', color: '#7C3AED' },
  { name: 'Wrestling', emoji: '🤼‍♂️', metric: 'mins', baseMET: 8.0, category: 'duration', color: '#F97316' },
  { name: 'Kung Fu', emoji: '🥋', metric: 'mins', baseMET: 7.0, category: 'duration', color: '#EA580C' },
  { name: 'Krav Maga', emoji: '🥋', metric: 'mins', baseMET: 8.5, category: 'duration', color: '#DC2626' },
  { name: 'Capoeira', emoji: '🤸‍♂️', metric: 'mins', baseMET: 6.8, category: 'duration', color: '#DB2777' },
  { name: 'Fencing', emoji: '🤺', metric: 'mins', baseMET: 6.0, category: 'duration', color: '#2563EB' },

  // Other / Generic
  { name: 'Other', emoji: '💪', metric: 'mins', baseMET: 4.0, category: 'duration', color: '#475569' },
];
