export const ROUTES = {
  SPLASH: 'Splash',
  DISCLAIMER: 'Disclaimer',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  PROFILE_SETUP: 'ProfileSetup',
  WELLNESS_PACING_PROFILE: 'WellnessPacingProfile',
  WELLNESS_PRESCRIPTION: 'WellnessPrescription',
  DRAWER: 'DrawerNavigator',
  DASHBOARD: 'Dashboard',
  ACTIVITY_TRACKING: 'ActivityTracking',
  NUTRITIONAL_PROFILER: 'NutritionalProfiler',
  LIFESTYLE_PROFILER: 'LifestyleProfiler',
  LEADERBOARD: 'Leaderboard',
  INSIGHTS: 'Insights',
  PROFILE: 'Profile',
  LEADERBOARD_DETAILS: 'LeaderboardDetails',
  DEMO_WORKOUT_LOG: 'DemoWorkoutLog',
  DEMO_SEARCH_HUB: 'DemoSearchHub',
  DEMO_WEARABLE_SYNC: 'DemoWearableSync',
  DEMO_POST_WORKOUT_SUMMARY: 'DemoPostWorkoutSummary',
  RESET_PASSWORD: 'ResetPassword',
} as const;

export type RouteType = typeof ROUTES[keyof typeof ROUTES];
