import { IQuestion } from './types';

export interface IStepInfo {
  stepIndex: number;
  sectionNumber: number;
  sectionTitle: string;
  sectionSubtitle: string;
  questionIds: (keyof import('./types').INBDPSketchPayload)[];
}

export const NBDP_STEPS: IStepInfo[] = [
  {
    stepIndex: 0,
    sectionNumber: 1,
    sectionTitle: 'Section 1: Inflammatory Processing & Glycogen Integrity',
    sectionSubtitle: 'Sugar frequency and complex carbohydrate foundations',
    questionIds: ['processed_sugar_frequency', 'glycogen_substrate_source'],
  },
  {
    stepIndex: 1,
    sectionNumber: 1,
    sectionTitle: 'Section 1: Inflammatory Processing & Glycogen Integrity',
    sectionSubtitle: 'Pre-workout and post-workout nutritional timing',
    questionIds: ['pre_workout_fueling_status', 'post_workout_intake_window'],
  },
  {
    stepIndex: 2,
    sectionNumber: 2,
    sectionTitle: 'Section 2: Hydration Depth & Osmotic Fluid Balance',
    sectionSubtitle: 'Daily water intake and distribution consistency',
    questionIds: ['daily_water_intake_liters', 'hydration_distribution_pattern'],
  },
  {
    stepIndex: 3,
    sectionNumber: 3,
    sectionTitle: 'Section 3: Sodium Processing & Cardiovascular Friction',
    sectionSubtitle: 'Packaged sodium exposure and table salt behavior',
    questionIds: ['processed_sodium_exposure', 'table_salt_behavior'],
  },
  {
    stepIndex: 4,
    sectionNumber: 4,
    sectionTitle: 'Section 4: Macro Quality, Cellular Repair, & Digestibility',
    sectionSubtitle: 'Protein density and healthy lipid foundations',
    questionIds: ['protein_intake_density', 'dominant_lipid_profile'],
  },
  {
    stepIndex: 5,
    sectionNumber: 4,
    sectionTitle: 'Section 4: Macro Quality, Cellular Repair, & Digestibility',
    sectionSubtitle: 'Microbiome live cultures and late-night digestion gaps',
    questionIds: ['microbiome_substrate_frequency', 'late_night_ingestion_gap'],
  },
  {
    stepIndex: 6,
    sectionNumber: 5,
    sectionTitle: 'Section 5: Preference Guardrails & Volume Envelopes',
    sectionSubtitle: 'Dietary archetypes, allergies, and portion envelopes',
    questionIds: ['dietary_archetype_profile', 'satiety_volume_envelope'],
  },
];

export const NBDP_QUESTIONS: Record<keyof import('./types').INBDPSketchPayload, IQuestion> = {
  processed_sugar_frequency: {
    id: 'processed_sugar_frequency',
    sectionNumber: 1,
    sectionTitle: 'Section 1: Inflammatory Processing & Glycogen Integrity',
    sectionSubtitle: 'Sugar Frequency',
    questionNumber: 1,
    title: 'How often do you consume foods containing added sugars, refined flour, or processed sweet snacks?',
    description: '(e.g., sodas, pastries, sweetened coffees, packaged desserts)',
    type: 'radio',
    options: [
      { label: 'Multiple times a day', value: 'Multiple times a day', description: 'Triggers System Inflammatory Flag', isFlag: true },
      { label: 'Daily', value: 'Daily', description: 'Triggers System Inflammatory Flag', isFlag: true },
      { label: 'Very High', value: 'Very High', description: 'Triggers System Inflammatory Flag', isFlag: true },
      { label: 'Frequently (3-5 times a week)', value: 'Frequently (3-5 times a week)' },
      { label: 'Rarely', value: 'Rarely' },
      { label: 'Never', value: 'Never' },
    ],
  },
  glycogen_substrate_source: {
    id: 'glycogen_substrate_source',
    sectionNumber: 1,
    sectionTitle: 'Section 1: Inflammatory Processing & Glycogen Integrity',
    sectionSubtitle: 'Carbohydrate Source',
    questionNumber: 2,
    title: 'What is your primary source of daily carbohydrates?',
    type: 'radio',
    options: [
      { label: 'Whole Grains & Starches', value: 'whole_grains', description: 'Whole grains, oats, brown rice, sweet potatoes' },
      { label: 'Refined Carbs', value: 'refined_carbs', description: 'White bread, white rice, standard pasta' },
      { label: 'Low Carb / Ketogenic', value: 'low_carb_ketogenic', description: 'Primarily fats and proteins, minimal starches' },
      { label: 'Mixed / Unstructured', value: 'mixed_unstructured', description: 'Unstructured mix of refined and whole sources' },
    ],
  },
  pre_workout_fueling_status: {
    id: 'pre_workout_fueling_status',
    sectionNumber: 1,
    sectionTitle: 'Section 1: Inflammatory Processing & Glycogen Integrity',
    sectionSubtitle: 'Pre-Workout Fueling',
    questionNumber: 3,
    title: 'What does your nutritional intake look like in the 2-hour window immediately leading up to an intense workout or long walk?',
    type: 'radio',
    options: [
      { label: 'Fasted', value: 'fasted', description: 'Completely fasted / empty stomach' },
      { label: 'Protein Only', value: 'protein_only', description: 'Protein shake or lean protein source only' },
      { label: 'Balanced Fuel', value: 'balanced_fuel', description: 'Easily digestible complex carbs + clean protein' },
      { label: 'High Sugar', value: 'high_sugar', description: 'Quick simple sugars / energy drinks / candy' },
    ],
  },
  post_workout_intake_window: {
    id: 'post_workout_intake_window',
    sectionNumber: 1,
    sectionTitle: 'Section 1: Inflammatory Processing & Glycogen Integrity',
    sectionSubtitle: 'Post-Workout Recovery',
    questionNumber: 4,
    title: 'How quickly do you consume a dedicated meal or protein/carbohydrate substrate after concluding a heavy exertion loop?',
    type: 'radio',
    options: [
      { label: 'Under 30 Minutes', value: 'under_30_mins', description: 'Anabolic window optimized: less than 30 minutes' },
      { label: '30 to 90 Minutes', value: '30_to_90_mins', description: 'Standard window: 30 to 90 minutes' },
      { label: 'Delayed (2+ Hours)', value: 'delayed_2_hours_plus', description: 'Delayed: more than 2 hours later' },
      { label: 'Unstructured', value: 'unstructured', description: 'No set pattern / depends on appetite' },
    ],
  },
  daily_water_intake_liters: {
    id: 'daily_water_intake_liters',
    sectionNumber: 2,
    sectionTitle: 'Section 2: Hydration Depth & Osmotic Fluid Balance',
    sectionSubtitle: 'Daily Fluid Volume',
    questionNumber: 5,
    title: 'On an average day, how much plain, pure water do you actively drink?',
    description: '(Excluding sugary beverages, high-sodium broths, and heavy caffeinated drinks)',
    type: 'slider',
    min: 0.0,
    max: 6.0,
    step: 0.25,
  },
  hydration_distribution_pattern: {
    id: 'hydration_distribution_pattern',
    sectionNumber: 2,
    sectionTitle: 'Section 2: Hydration Depth & Osmotic Fluid Balance',
    sectionSubtitle: 'Hydration Flow',
    questionNumber: 6,
    title: 'How do you distribute your fluid intake throughout your active physiological day?',
    type: 'radio',
    options: [
      { label: 'Consistent Hourly', value: 'consistent_hourly', description: 'Steady, measured amounts consumed every hour' },
      { label: 'Bulk Consumption', value: 'bulk_consumption', description: 'Large amounts gulped down at long, irregular intervals' },
      { label: 'Primarily With Meals', value: 'primarily_with_meals', description: 'Drank almost exclusively during breakfast/lunch/dinner' },
      { label: 'Reactive Thirst', value: 'reactive_thirst', description: 'Only consumed when feeling noticeably parched or dehydrated' },
    ],
  },
  processed_sodium_exposure: {
    id: 'processed_sodium_exposure',
    sectionNumber: 3,
    sectionTitle: 'Section 3: Sodium Processing & Cardiovascular Friction',
    sectionSubtitle: 'Sodium Exposure',
    questionNumber: 7,
    title: 'How frequently do your daily meals incorporate highly processed packaged products, canned goods, frozen entrees, or savory snacks?',
    type: 'radio',
    options: [
      { label: 'Multiple Daily', value: 'multiple_daily', description: 'Every meal contains a packaged or commercial element' },
      { label: 'Once Daily', value: 'once_daily', description: 'One meal or snack cycle per day relies on processed items' },
      { label: 'Occasional', value: 'occasional', description: 'A few times a week' },
      { label: 'Minimal', value: 'minimal', description: 'Freshly prepared whole foods cooked from scratch almost exclusively' },
    ],
  },
  table_salt_behavior: {
    id: 'table_salt_behavior',
    sectionNumber: 3,
    sectionTitle: 'Section 3: Sodium Processing & Cardiovascular Friction',
    sectionSubtitle: 'Table Salt Habit',
    questionNumber: 8,
    title: 'What is your behavioral habit regarding adding extra salt to your food at the dinner table?',
    type: 'radio',
    options: [
      { label: 'Always Before Tasting', value: 'always_before_tasting', description: 'Add salt automatically before taking the first bite' },
      { label: 'Taste Then Add', value: 'taste_then_add', description: 'Taste the food first, then frequently add extra salt' },
      { label: 'Rarely Add', value: 'rarely_add', description: 'Rarely add extra salt if the dish was seasoned during cooking' },
      { label: 'Monitored Low Sodium', value: 'monitored_low_sodium', description: 'Actively minimize all salt addition due to medical guidelines' },
    ],
  },
  protein_intake_density: {
    id: 'protein_intake_density',
    sectionNumber: 4,
    sectionTitle: 'Section 4: Macro Quality, Cellular Repair, & Digestibility',
    sectionSubtitle: 'Protein Density',
    questionNumber: 9,
    title: 'Choose the selection that best describes your targeted consumption of protein blocks:',
    description: '(e.g., eggs, chicken, fish, tofu, paneer, lentils, protein supplements)',
    type: 'radio',
    options: [
      { label: 'Optimized High', value: 'optimized_high', description: 'Prioritized at every single meal zone' },
      { label: 'Moderate Adequate', value: 'moderate_adequate', description: 'Present in at least 2 primary meals a day' },
      { label: 'Low / Unstructured', value: 'low_unstructured', description: 'Occasional or secondary component of meals' },
      { label: 'Deficient', value: 'deficient', description: 'Rarely trace or explicitly measure macro protein distribution' },
    ],
  },
  dominant_lipid_profile: {
    id: 'dominant_lipid_profile',
    sectionNumber: 4,
    sectionTitle: 'Section 4: Macro Quality, Cellular Repair, & Digestibility',
    sectionSubtitle: 'Dietary Fat Sources',
    questionNumber: 10,
    title: 'What are the dominant sources of dietary fats in your typical food intake? (Select all that apply)',
    type: 'checkbox',
    options: [
      { label: 'Monounsaturated', value: 'monounsaturated', description: 'Olive oil, avocados, raw nuts' },
      { label: 'Omega-3 Fatty Acids', value: 'omega_3_fatty_acids', description: 'Fish oil, walnuts, chia seeds, fatty fish' },
      { label: 'Saturated Animal Fats', value: 'saturated_animal_fats', description: 'Butter, ghee, lard, heavy cream, red meats' },
      { label: 'Trans / Hydrogenated', value: 'trans_hydrogenated', description: 'Margarine, commercial frying oils, fast-food lipids' },
    ],
  },
  microbiome_substrate_frequency: {
    id: 'microbiome_substrate_frequency',
    sectionNumber: 4,
    sectionTitle: 'Section 4: Macro Quality, Cellular Repair, & Digestibility',
    sectionSubtitle: 'Microbiome & Fermented Foods',
    questionNumber: 11,
    title: 'How often do you incorporate fermented, live-culture substrates (e.g., yogurt, kefir, kombucha, kimchi) or prebiotic fibers into your diet?',
    type: 'radio',
    options: [
      { label: 'Daily', value: 'daily', description: 'At least one serving consumed every day' },
      { label: 'Frequently', value: 'frequently', description: '3-4 times per week' },
      { label: 'Rarely', value: 'rarely', description: 'Less than once a week' },
      { label: 'Never', value: 'never', description: 'Do not consume fermented food substrates' },
    ],
  },
  late_night_ingestion_gap: {
    id: 'late_night_ingestion_gap',
    sectionNumber: 4,
    sectionTitle: 'Section 4: Macro Quality, Cellular Repair, & Digestibility',
    sectionSubtitle: 'Late-Night Ingestion Gap',
    questionNumber: 12,
    title: 'What is the standard duration of the time gap between your final calorie intake and your evening sleep window?',
    type: 'radio',
    options: [
      { label: 'Greater than 3 Hours', value: 'greater_than_3_hours', description: 'Optimal clearance: more than 3 hours before sleep' },
      { label: '2 to 3 Hours', value: '2_to_3_hours', description: 'Moderate clearance: 2 to 3 hours before sleep' },
      { label: '1 to 2 Hours', value: '1_to_2_hours', description: 'Short window: 1 to 2 hours before sleep' },
      { label: 'Less than 1 Hour', value: 'less_than_1_hour', description: 'High strain: consume food right up until going to bed' },
    ],
  },
  dietary_archetype_profile: {
    id: 'dietary_archetype_profile',
    sectionNumber: 5,
    sectionTitle: 'Section 5: Preference Guardrails & Volume Envelopes',
    sectionSubtitle: 'Dietary Archetypes & Exclusions',
    questionNumber: 13,
    title: 'Select your foundational dietary profile and indicate any absolute ingredient exclusions or allergies: (Select all that apply)',
    type: 'checkbox',
    options: [
      { label: 'Omnivore (Non-Veg)', value: 'omnivore_non_veg', description: 'Standard Non-Vegetarian / Consumes all proteins' },
      { label: 'Pescatarian', value: 'pescatarian', description: 'Fish and plant-based proteins only' },
      { label: 'Vegetarian', value: 'vegetarian', description: 'Dairy/plants, no meat or fish' },
      { label: 'Vegan', value: 'vegan', description: 'Strictly plant-based, no animal derivatives' },
      { label: 'Nut Allergy Exclusion', value: 'allergy_excl_nuts', description: 'Strictly exclude all nuts' },
      { label: 'Dairy Allergy Exclusion', value: 'allergy_excl_dairy', description: 'Lactose / dairy protein free' },
      { label: 'Gluten Allergy Exclusion', value: 'allergy_excl_gluten', description: 'Celiac / gluten free' },
    ],
  },
  satiety_volume_envelope: {
    id: 'satiety_volume_envelope',
    sectionNumber: 5,
    sectionTitle: 'Section 5: Preference Guardrails & Volume Envelopes',
    sectionSubtitle: 'Portion & Satiety Volume',
    questionNumber: 14,
    title: 'How would you describe your typical daily eating capacity and portion sizes relative to your satiety (fullness)?',
    type: 'radio',
    options: [
      { label: 'Calorie-Dense, Low Volume', value: 'calorie_dense_low_volume', description: 'Eat small meals but they tend to be heavy/rich' },
      { label: 'High-Volume Overeating', value: 'high_volume_overeating', description: 'Tend to eat very large portions and push past fullness' },
      { label: 'Grazing Pattern', value: 'grazing_pattern', description: 'Eat frequent small amounts throughout the day, rarely full meals' },
      { label: 'Suppressed Under-Eating', value: 'suppressed_under_eating', description: 'Often skip meals or forget to eat due to high work stress' },
    ],
  },
};
